### ISSUE TITLE
PublishSubscribe Sample Only Use SQLServer

### ISSUE THREAD

**Issue by zhuanggq** [Shuttle/shuttle-esb#57]
Are there any Samples only used SQLServer to  implement Publish Subscribe？thanks

**Comment by eben-roux** [comment]
The [publish/subscribe sample](https://github.com/Shuttle/Shuttle.Esb.Samples/tree/master/Shuttle.PublishSubscribe) makes use of a Sql Server database for the subscription store and *Msmq* for the queues.

If you would like to use Sql Server tables as queues you could change the configuration files as follows (while keeping the 'Subscription' connection string name):

> Shuttle.Esb.Samples/Shuttle.PublishSubscribe/Shuttle.PublishSubscribe.Server/App.config

``` xml
<configuration>
	<configSections>
		<section name='serviceBus' type="Shuttle.Esb.ServiceBusSection, Shuttle.Esb"/>
	</configSections>

	<connectionStrings>
		<add name="Subscription"
			 connectionString="Data Source=.\sqlexpress;Initial Catalog=shuttle;Integrated Security=SSPI;"
			 providerName="System.Data.SqlClient"/>
	</connectionStrings>

	<serviceBus>
		<inbox
		   workQueueUri="sql://subscription/shuttle-server-work"
		   errorQueueUri="sql://subscription/shuttle-error" />
	</serviceBus>
</configuration>
```

> Shuttle.Esb.Samples/Shuttle.PublishSubscribe/Shuttle.PublishSubscribe.Subscriber/App.config

``` xml
<configuration>
	<configSections>
		<section name='serviceBus' type="Shuttle.Esb.ServiceBusSection, Shuttle.Esb"/>
	</configSections>

	<connectionStrings>
		<add name="Subscription"
			 connectionString="Data Source=.\sqlexpress;Initial Catalog=shuttle;Integrated Security=SSPI;"
			 providerName="System.Data.SqlClient"/>
	</connectionStrings>

	<serviceBus>
		<inbox
		   workQueueUri="sql://subscription/shuttle-subscriber-work"
		   errorQueueUri="sql://subscription/shuttle-error" />
	</serviceBus>
</configuration>
```

> Shuttle.Esb.Samples/Shuttle.PublishSubscribe/Shuttle.PublishSubscribe.Client/App.config

``` xml
<configuration>
	<configSections>
		<section name='serviceBus' type="Shuttle.Esb.ServiceBusSection, Shuttle.Esb"/>
	</configSections>

	<connectionStrings>
		<add name="shuttle"
			 connectionString="Data Source=.\sqlexpress;Initial Catalog=shuttle;Integrated Security=SSPI;"
			 providerName="System.Data.SqlClient"/>
	</connectionStrings>

	<serviceBus>
		<messageRoutes>
			<messageRoute uri="sql://shuttle/shuttle-server-work">
				<add specification="StartsWith" value="Shuttle.PublishSubscribe.Messages" />
			</messageRoute>
		</messageRoutes>
	</serviceBus>

	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
	</startup>
</configuration>
```

You will notice that in the `Shuttle.PublishSubscribe.Client` app.config file I used `shuttle` for the connection string name since there wasn't a connection string defined.  The name could be anything but this is just to demonstrate how to set it up.

More information can be found in [the Sql Server implementation documentation](http://shuttle.github.io/shuttle-esb/implementations-sql-server/).

Please ask any other questions if I haven't understood you correctly.
