### ISSUE TITLE
Intended level of support going forwards

### ISSUE THREAD

**Issue by RACTI179** [Shuttle/shuttle-esb#74]
Hey Eben,

Apologies if this is not the right way to ask, but I'm keen to understand the path going forward for Shuttle.  The documentation currently states that .NET Core 2.1 is supported (rather than more recent versions), but that version is scheduled to go out of Microsoft support next month (August 2021)

Is the intention to continue to support Shuttle going forward?

(Fwiw... we've been using Shuttle within our company for several years, with great success. We implemented it at low cost, and it's been reliable and served its purpose extremely well.)

Thanks!

**Comment by eben-roux** [comment]
Hi Clayton,

I've been meaning to update the documentation a bit for some time but I just don't get time :)

That being said, the packages typically target standard:

```
<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
```

Some older ones may still target `net461` and `netcoreapp2.1` but would also include at least `netstandard2.0`.  When I come across one that does not target standard only I do update them,

I tinker on the Shuttle components every-so-often, but mostly only when required.

Great to hear that it has served you well :)

I will get around to updating the documentation as soon as I can... just to avoid any confusion.  At a minimum I'll update that version bit... soon.

**Comment by RACTI179** [comment]
Okay fantastic, thanks for your fast response Eben.

So am I correct in thinking that this means full support for .NET 5, given that supports Standard 2.1 and lower?

**Comment by eben-roux** [comment]
.NET 5 would use the .NET Standard 2.1 package, yes.

I *could*, of course, add a target to .NET 5 but since I'm not using anything specific to .NET 5 it doesn't seem necessary at this stage.  Even so, introducing .NET 5-only functionality would result in conditional compilation and the like.  This is something that *may* be required in future. 

Currently the [ServiceHost](https://github.com/Shuttle/Shuttle.Core.ServiceHost/blob/master/Shuttle.Core.ServiceHost/Shuttle.Core.ServiceHost.csproj) targets implementations (`net461;netcoreapp2.1`) since the package serves a rather specific purpose.  This results in conditional compilation requirements as can be seen in the [ConsoleService](https://github.com/Shuttle/Shuttle.Core.ServiceHost/blob/master/Shuttle.Core.ServiceHost/ConsoleService.cs) class.  .NET 5 targeting would seem appropriate here.

If you *do* happen upon anything that you feel requires any updating you are absolutely welcome to let me know.

**Comment by RACTI179** [comment]
That all makes sense, thanks again Eben.
Thanks too for your fast responses, they are always much appreciated!

I'll close this as you've answered my questions, thanks.
